### PR TITLE
Adds support for PHP 8.4 and psr/http-message 2.x

### PR DESCRIPTION
**Pull request by compwright**
Upgrades middlewares/utils to v4 and supporting dev dependencies

### CODE REVIEW

**Comment by oscarotero** [comment]
thanks, but your change breaks in Php7.
Can you update the dependencies maintaining compatibility with older versions? Take a look to this example: https://github.com/middlewares/trailing-slash/blob/master/composer.json#L19-L30

**Comment by compwright** [comment]
@oscarotero IMO we shouldn't be supporting PHP 7.4 anymore, it's EOL. See https://www.php.net/supported-versions.php

This PR should result in a major version release as a result.

**Comment by oscarotero** [comment]
I don't want to release a major version for this, specially if supporting php 7.x doesn't require any change in the code, only in the dependencies.

**Comment by compwright** [comment]
@oscarotero the key change is this line:

```
"middlewares/utils": "^4.0",
```

Per your package.json, middlewares/utils v4 requires PHP 8.1. Therefore, this upgrade also requires a higher minimum version of PHP.

**Comment by oscarotero** [comment]
You can define both versions with `"middlewares/utils": "^3.0 || ^4.0"`. Composer will install the highest version compatible with your php version.

Take a look at the example in my first comment.

**Comment by compwright** [comment]
@oscarotero good point, updated per your request.

**Comment by oscarotero** [comment]
Thank you!

**Pull request merged**
